# Cloud Build configuration for Flutter web app deployment
steps:
  # Install Flutter and dependencies
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Install Flutter
        git clone https://github.com/flutter/flutter.git -b stable
        export PATH="$PATH:/workspace/flutter/bin"
        
        # Verify Flutter installation
        flutter doctor
        
        # Get dependencies
        flutter pub get
        
        # Build Flutter web app
        flutter build web --release --web-renderer canvaskit
        
        # Create a simple server for the built files
        echo 'FROM nginx:alpine
        COPY build/web /usr/share/nginx/html
        COPY nginx.conf /etc/nginx/nginx.conf
        EXPOSE 8080
        CMD ["nginx", "-g", "daemon off;"]' > Dockerfile
        
        echo 'events {
          worker_connections 1024;
        }
        http {
          include /etc/nginx/mime.types;
          default_type application/octet-stream;
          sendfile on;
          keepalive_timeout 65;
          
          server {
            listen 8080;
            server_name localhost;
            root /usr/share/nginx/html;
            index index.html;
            
            # Handle Flutter web routing
            location / {
              try_files $uri $uri/ /index.html;
            }
            
            # Cache static assets
            location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
              expires 1y;
              add_header Cache-Control "public, immutable";
            }
            
            # Security headers
            add_header X-Frame-Options "SAMEORIGIN" always;
            add_header X-Content-Type-Options "nosniff" always;
            add_header X-XSS-Protection "1; mode=block" always;
          }
        }' > nginx.conf

  # Build and push Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/guideian-web:$COMMIT_SHA', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/guideian-web:$COMMIT_SHA']

  # Deploy to App Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'guideian-web'
      - '--image'
      - 'gcr.io/$PROJECT_ID/guideian-web:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '1'

# Store images in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/guideian-web:$COMMIT_SHA'

# Build options
options:
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: '100'
  logging: CLOUD_LOGGING_ONLY

