// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB41Go0wudzjur1xcPO4t-_gk9fGYccgg4',
    appId: '1:723263641111:web:e9a4b24c08e0dee71e6e52',
    messagingSenderId: '723263641111',
    projectId: 'guideian-b5eb4',
    authDomain: 'guideian-b5eb4.firebaseapp.com',
    databaseURL: 'https://guideian-b5eb4-default-rtdb.firebaseio.com',
    storageBucket: 'guideian-b5eb4.firebasestorage.app',
    measurementId: 'G-2B96N983EH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQl2GBWQqenIGdczcJo54ZkYiZE0BPW6Q',
    appId: '1:723263641111:android:f452b19b7da392871e6e52',
    messagingSenderId: '723263641111',
    projectId: 'guideian-b5eb4',
    databaseURL: 'https://guideian-b5eb4-default-rtdb.firebaseio.com',
    storageBucket: 'guideian-b5eb4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAO58E6PV82p4iJvF_TOr7JVkLsmmPCXPM',
    appId: '1:723263641111:ios:c3d080794c38e8151e6e52',
    messagingSenderId: '723263641111',
    projectId: 'guideian-b5eb4',
    databaseURL: 'https://guideian-b5eb4-default-rtdb.firebaseio.com',
    storageBucket: 'guideian-b5eb4.firebasestorage.app',
    iosBundleId: 'com.guideian.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAO58E6PV82p4iJvF_TOr7JVkLsmmPCXPM',
    appId: '1:723263641111:ios:c3d080794c38e8151e6e52',
    messagingSenderId: '723263641111',
    projectId: 'guideian-b5eb4',
    databaseURL: 'https://guideian-b5eb4-default-rtdb.firebaseio.com',
    storageBucket: 'guideian-b5eb4.firebasestorage.app',
    iosBundleId: 'com.guideian.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB41Go0wudzjur1xcPO4t-_gk9fGYccgg4',
    appId: '1:723263641111:web:e9a4b24c08e0dee71e6e52',
    messagingSenderId: '723263641111',
    projectId: 'guideian-b5eb4',
    authDomain: 'guideian-b5eb4.firebaseapp.com',
    databaseURL: 'https://guideian-b5eb4-default-rtdb.firebaseio.com',
    storageBucket: 'guideian-b5eb4.firebasestorage.app',
  );
}
