name: Flutter Quick Test

on:
  push:
    branches: [ main, recover-commit ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Quick Test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.0'
        channel: 'stable'
        
    - name: Get dependencies
      run: |
        cd guideian_app
        flutter pub get
        
    - name: Format check
      run: |
        cd guideian_app
        flutter format --dry-run --set-exit-if-changed .
        
    - name: Analyze code
      run: |
        cd guideian_app
        flutter analyze
        
    - name: Run tests
      run: |
        cd guideian_app
        flutter test
